changelog:
  categories:
    - title: User impact 🛠
      labels:
        - release-notes:user-impact
    - title: Breaking Changes 🛠
      labels:
        - release-notes:breaking-change
    - title: New Features 🎉
      labels:
        - release-notes:new-feature
    - title: Improvements
      labels:
        - release-notes:improvement
    - title: Bug Fixes
      labels:
        - release-notes:bug-fix
    - title: Maintenance
      labels:
        - release-notes:maintenance
    - title: Dependencies
      labels:
        - release-notes:dependency
    - title: Other Changes
      labels:
        - release-notes:misc
        - "*"
