changelog:
  exclude:
    labels:
        - release-notes:skip
        - release-notes:flaky-test-fix
        - release-notes:unreleased-feature-changes
        - release-notes:unreleased-bug-fix
        - release-notes:formatting
  categories:
    - title: User impact 🛠
      labels:
        - release-notes:user-impact
    - title: Breaking Changes 🛠
      labels:
        - release-notes:breaking-change
    - title: New Features 🎉
      labels:
        - release-notes:new-feature
    - title: Improvements
      labels:
        - release-notes:improvement
    - title: Bug Fixes
      labels:
        - release-notes:bug-fix
    - title: Maintenance
      labels:
        - release-notes:maintenance
        - release-notes:logging
        - release-notes:refactor
    - title: Documentation changes
      labels:
        - release-notes:documentation-changes
    - title: Build System
      labels:
        - release-notes:build-system
    - title: Dependencies
      labels:
        - release-notes:dependency
    - title: Other Changes
      labels:
        - release-notes:misc
        - "*"
