repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: no-commit-to-branch
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: test-data/eclipse/parse/ERROR.PRT # exact format is needed for testing

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
