repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: no-commit-to-branch
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: test-data/eclipse/parse/ERROR.PRT # exact format is needed for testing

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.3
    hooks:
    - id: clang-format
      args: [ --style=file, --Werror]
      exclude: .json

-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
    - id: cmake-lint
      exclude: FindFilesystem
      args: [ "--disable:C0301,C0111,C0113" ]
