repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: no-commit-to-branch
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4
    hooks:
    -   id: pylint

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
