repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    - id: ruff
      args: [ --fix ]

-   repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.5
    hooks:
    - id: clang-format
      args: [ --style=file, --Werror]
      exclude: .json

-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
    - id: cmake-lint
      exclude: FindFilesystem
      args: [ "--disable:C0301,C0111,C0113" ]
