version: 2

sphinx:
   configuration: docs/conf.py

python:
   install:
   - requirements: dev-requirements.txt
   - method: pip
     path: .

sphinx:
  builder: html
  configuration: docs/rst/manual/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - cmake
    - libblas-dev
    - liblapack-dev
