version: 2

sphinx:
   configuration: docs/conf.py

python:
   version: 3.7
   install:
   - requirements: dev-requirements.txt
   - method: pip
     path: .

sphinx:
  builder: html
  configuration: docs/rst/manual/conf.py

build:
  apt_packages:
    - cmake
    - libblas-dev
    - liblapack-dev
