language: c

language: python
python:
  - "3.6"

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: linux
      compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - liblapack-dev
      - valgrind
      - gcc-4.8
      - g++-4.8
      - clang
      - cmake
      - cmake-data

install:
    - if [[ "$CC" == "gcc" ]]; then export CXX="g++-4.8"; fi

    

env:
  global:
     - ERT_SHOW_BACKTRACE=1


script:
  - travis/build_total.py ert
