language: python
dist: xenial
python:
  - 3.6

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode8.3
sudo: false

env:
  global:
    - ERT_SHOW_BACKTRACE=1
    - INSTALL_DIR="$(pwd)/ert_env"
    - LD_LIBRARY_PATH="${INSTALL_DIR}/lib:${INSTALL_DIR}/lib64"
    - DYLD_LIBRARY_PATH="${INSTALL_DIR}/lib:${INSTALL_DIR}/lib64"

  matrix:
    - PYTHON_VERSION=3.6

matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - liblapack-dev
      - valgrind
      - clang
      - cmake
      - cmake-data
      - libxcb-image0
      - libxcb-icccm4
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-xinerama0

before_install:
    - export TRAVIS_PYTHON_VERSION="3.6";

    # We do this conditionally because it saves us some downloading if the version is the same.
    # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    #     wget https://repo.continuum.io/miniconda/Miniconda3-4.4.10-MacOSX-x86_64.sh -O miniconda.sh;
    #   else
    #     wget https://repo.continuum.io/miniconda/Miniconda3-4.4.10-Linux-x86_64.sh -O miniconda.sh;
    #   fi

    # - bash miniconda.sh -b -p $HOME/miniconda
    # - export CONDA_HOME="$HOME/miniconda"
    # - export PATH="$CONDA_HOME/bin:$PATH"
    # - conda create -n ert_env pyqt python=$TRAVIS_PYTHON_VERSION --yes;
    # - source activate ert_env
    - python -m venv ert_env
    # Checkout libres - need libecl version
    - source .libres_version
    - git clone --branch $LIBRES_VERSION --depth 1 https://github.com/equinor/libres
    - pushd libres
    - source .libecl_version
    - popd
    - git clone --branch $LIBECL_VERSION --depth 1 https://github.com/equinor/libecl

install:
  # For now we have to make install libecl.
  # Remove when it's possible to pip install
  - bash .build_install.sh libecl
  - bash .build_install.sh libres

script:
  #- export PYTHONPATH=$INSTALL_DIR/lib/python$TRAVIS_PYTHON_VERSION/dist-packages:$PYTHONPATH
  #- export PYTHONPATH=$INSTALL_DIR/lib/python$TRAVIS_PYTHON_VERSION/site-packages:$PYTHONPATH
  #- export PATH=$INSTALL_DIR/bin:$PATH
  #- echo $PATH
  #- echo $PYTHONPATH
  - pip install -r dev-requirements.txt
  - pip install .
  # For easy compare of installed versions once a version fails
  - pip list
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      xvfb-run -s "-screen 0 640x480x24" python setup.py test;
    else
      python setup.py test;
    fi
  - sphinx-build -n -v -E -W ./docs/rst/manual ./tmp/ert_docs
  - pip uninstall PyQt5
  - ert --help
