language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode8.3
sudo: false
dist: xenial

env:
  global:
    - ERT_SHOW_BACKTRACE=1

  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6

matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - liblapack-dev
      - valgrind
      - clang
      - cmake
      - cmake-data

before_install:
    - if [[ $PYTHON_VERSION == 2.7 ]]; then
        export TRAVIS_PYTHON_VERSION="2.7";
        export PYTEST_QT_API="pyqt4v2";
      else
        export TRAVIS_PYTHON_VERSION="3.6";
      fi

    # We do this conditionally because it saves us some downloading if the version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
      else
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-4.4.10-MacOSX-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-4.4.10-Linux-x86_64.sh -O miniconda.sh;
        fi
      fi

    - bash miniconda.sh -b -p $HOME/miniconda
    - export CONDA_HOME="$HOME/miniconda"
    - export PATH="$CONDA_HOME/bin:$PATH"
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        conda config --set restore_free_channel true;        
        conda create -n ert_env pyqt=4.11.3 python=2.7 --yes;
      else
        conda create -n ert_env python=$TRAVIS_PYTHON_VERSION --yes;
      fi
    - source activate ert_env

install:
  - pip install -r dev-requirements.txt
  - pip install .

script:
  # For easy compare of installed versions once a version fails
  - pip list
  - rm -r ert*
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      xvfb-run python setup.py test
    else
      python setup.py test
    fi
  - sphinx-build -n -v -E -W ./docs/rst/manual ./tmp/ert_docs
  - conda remove pyqt -y
  - ert --help
