[build-system]

requires = [
    "setuptools<64",
    "setuptools_scm[toml]>=6.2",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "ecl",
    "conan",
    "pybind11>=2.10.0",  # If this comes out of sync with the version installed by Conan please update the version in CMakeLists
    "grpcio-tools==1.41.0",
]


[tool.pytest.ini_options]
addopts = "-ra --strict-markers"
markers = [
    "consumer_driven_contract_test",
    "consumer_driven_contract_verification",
    "integration_test",
    "quick_only",
    "requires_eclipse",
    "requires_ert_storage",
    "requires_window_manager",
    "script",
    "slow",
    "unstable",
]
log_cli = "false"
asyncio_mode = "auto"

[tool.isort]
profile = "black"

[tool.setuptools_scm]
write_to = "src/ert/shared/version.py"
