[build-system]

requires = [
    "setuptools<64",
    "setuptools_scm[toml]>=6.2",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "ecl",
    "conan<2",
    "pybind11>=2.10.0",  # If this comes out of sync with the version installed by Conan please update the version in CMakeLists
    "grpcio-tools",
]


[tool.pytest.ini_options]
addopts = "-ra --strict-markers"
markers = [
    "integration_test",
    "quick_only",
    "requires_eclipse",
    "requires_ert_storage",
    "requires_window_manager",
    "script",
    "slow",
    "unstable",
]
log_cli = "false"
asyncio_mode = "auto"

[tool.isort]
profile = "black"

[tool.black]
include = '(\.pyi?|\.ipynb|\.py\.j2)$'

[tool.setuptools_scm]
write_to = "src/ert/shared/version.py"

[tool.flake8]
per-file-ignores = [
    # Ignore all protobuf v2 files
    "*_pb2.py: E"
]
ignore = [
    # whitespace before ':', solved by black:
    "E203",
    # line break before binary operator, solved by black:
    "W503",
    # The minimal set of ignores that makes flake8 pass when flake8-bugbear is installed:
    "B019"
]
max-line-length = 88
