-
  name: OP1_PERSISTENCE # e.g. group name
  distribution:
    input:
      lower_bound: 0.01
      upper_bound: 0.4
    type: uniform
  variables:
  - OP1_PERSISTENCE
  type: stochastic

-
  name: OP1_OCTAVES
  distribution:
    input:
      lower_bound: 3.0
      upper_bound: 5.0
    type: uniform
  variables:
  - OP1_OCTAVES
  type: stochastic
- distribution:
    input:
      lower_bound: 0.25
      upper_bound: 1.25
    type: uniform
  variables:
  - OP1_DIVERGENCE_SCALE
  name: OP1_DIVERGENCE_SCALE
  type: stochastic
- distribution:
    input:
      lower_bound: -0.1
      upper_bound: 0.1
    type: uniform
  variables:
  - OP1_OFFSET
  name: OP1_OFFSET
  type: stochastic
- distribution:
    input:
      lower_bound: 0.1
      upper_bound: 0.6
    type: uniform
  variables:
  - OP2_PERSISTENCE
  name: OP2_PERSISTENCE
  type: stochastic
- distribution:
    input:
      lower_bound: 5.0
      upper_bound: 12.0
    type: uniform
  variables:
  - OP2_OCTAVES
  name: OP2_OCTAVES
  type: stochastic
- distribution:
    input:
      lower_bound: 0.5
      upper_bound: 1.5
    type: uniform
  variables:
  - OP2_DIVERGENCE_SCALE
  name: OP2_DIVERGENCE_SCALE
  type: stochastic
- distribution:
    input:
      lower_bound: -0.2
      upper_bound: 0.2
    type: uniform
  variables:
  - OP2_OFFSET
  name: OP2_OFFSET
  type: stochastic
- distribution:
    input:
      lower_bound: 0.1
      upper_bound: 0.5
    type: uniform
  variables:
  - BPR_555_PERSISTENCE
  name: BPR_555_PERSISTENCE
  type: stochastic
- distribution:
    input:
      lower_bound: 0.2
      upper_bound: 0.7
    type: uniform
  variables:
  - BPR_138_PERSISTENCE
  name: BPR_138_PERSISTENCE
  type: stochastic
