env:
  LM_LICENSE_FILE: license@company.com
  F_UFMTENDIAN: big
  ARCH: x86_64

eclrun_env:
  SLBSLS_LICENSE_FILE: something@yourcompany.com
  ECLPATH: /path/to/ecl
  PATH: /path/to/ecl/macros
  LSB_JOBID: null
