name: Annotate Python

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  annotate-python-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: -1
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install flake8
        run: pip install flake8 flake8-bugbear flake8-simplify flake8-debugger flake8-pep3101
      - name: install mypy
        run: pip install -r types-requirements.txt
      - name: install project
        run: pip install .
      - name: find changed files
        id: find_changed_files
        run: echo ::set-output name=changed_files::$(git diff --name-only ${{github.sha}} ${{github.event.pull_request.base.sha}} | tr ' ' '\n' |  xargs ls -d 2>/dev/null | grep -E ".py$" | tr '\n' ' ')
      - run: echo ::add-matcher::.github/flake8-matcher.json
      - name: run flake8
        run: flake8 --exit-zero ${{steps.find_changed_files.outputs.changed_files}}
        if: steps.find_changed_files.outputs.changed_files != ''
      - run: echo ::add-matcher::.github/mypy-matcher.json
      - name: run mypy
        run: mypy ${{steps.find_changed_files.outputs.changed_files}} --config-file .mypy-annotate.ini
        if: steps.find_changed_files.outputs.changed_files != ''
        continue-on-error: true
