on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
jobs:

  build-wheels:
    timeout-minutes: 30
    strategy:
      fail-fast: false

    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Build Linux Wheel
      uses: docker://quay.io/pypa/manylinux2014_x86_64
      with:
        entrypoint: /github/workspace/ci/github/build_linux_wheel.sh
        args: ${{ inputs.python-version }}
      if: inputs.os == 'ubuntu-latest'

    - name: Build macOS Wheel
      run: pip wheel . --no-deps -w dist
      if: inputs.os == 'macos-latest'

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.os }} Python ${{ inputs.python-version }} wheel
        path: dist/*
