name: Python package

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

env:
  ERT_SHOW_BACKTRACE: 1
  ECL_SKIP_SIGNAL: 1

jobs:
  build-test-cmake:
    name: CMake

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y valgrind

    - name: Install dependencies from PyPI
      run: |
        python3 -m pip install conan pybind11

    - name: Build libecl
      run: |
        git clone https://github.com/equinor/libecl
        mkdir libecl/build
        cmake -S libecl -B libecl/build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build libecl/build --target install
        sudo rm -rf libecl

    - name: Build libres
      run: |
        mkdir cmake-build
        cmake -S libres -B cmake-build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTS=ON -DCOVERAGE=ON
        cmake --build cmake-build -j2

    - name: Run tests
      run: |
        cd cmake-build
        export PATH=$PWD/bin:$PATH
        ctest --output-on-failure

    - name: Install gcovr
      run: |
        python3 -m pip install gcovr

    - name: generate coverage report
      run: |
        gcovr -r libres/ --exclude-directories ".*tests" cmake-build/ --xml -o cov.xml

    - name: Upload c coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: cov.xml

  build-wheels:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: './.github/actions/install_dependencies'
      with:
        os: ${{ matrix.os }}

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build Linux Wheel
      uses: docker://quay.io/pypa/manylinux2014_x86_64
      with:
        entrypoint: /github/workspace/ci/github/build_linux_wheel.sh
        args: ${{ matrix.python-version }}
      if: matrix.os == 'ubuntu-latest'

    - name: Build macOS Wheel
      run: pip wheel . --no-deps -w dist
      if: matrix.os == 'macos-latest'

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }} Python ${{ matrix.python-version }} wheel
        path: dist/*

  tests-ert:
    name: Run ert tests
    needs: [build-wheels]
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest]
        test-type: ['integration-tests', 'unit-tests']
        # Excluded to keep build times down on Github actions
        exclude:
          - os: macos-latest
            python-version: '3.9'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: './.github/actions/install_dependencies'
      with:
        os: ${{ matrix.os }}

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get wheels
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.os }} Python ${{ matrix.python-version }} wheel

    - name: Install wheel and test dependencies
      run: |
        find . -name "*.whl" -exec pip install {} \;
        pip install -r dev-requirements.txt

    - name: Test Ubuntu
      if: matrix.os == 'ubuntu-latest' && matrix.test-type == 'unit-tests'
      env:
        DISPLAY: ':99.0'
      run: |
        ci/github/start_herbstluftwm.sh &
        sleep 5
        pushd tests
        pytest ert_tests -sv --durations=0 -m "not integration_test"

    - name: Test MacOS
      if: matrix.os == 'macos-latest' && matrix.test-type == 'unit-tests'
      run: |
        pushd tests
        pytest ert_tests -sv --durations=0 -m "not integration_test"

    - name: Integration Test Ubuntu
      if: matrix.os == 'ubuntu-latest' && matrix.test-type == 'integration-tests'
      env:
        DISPLAY: ':99.0'
      run: |
        ci/github/start_herbstluftwm.sh &
        sleep 5
        pushd tests
        pytest ert_tests performance_tests -sv --durations=0 -m "integration_test"

    - name: Integration Test MacOS
      if: matrix.os == 'macos-latest' && matrix.test-type == 'integration-tests'
      run: |
        pushd tests
        pytest ert_tests performance_tests -sv --durations=0 -m "integration_test"

    - name: Test for a clean repository
      run: |
        # Run this before the 'Test CLI' entry below, which produces a few files that are accepted for now. Exclude the wheel.
        git status --porcelain | sed '/ert.*.whl$/d'
        test -z "$(git status --porcelain | sed '/ert.*.whl$/d')"

    - name: Test CLI
      run: |
        ert --help


  docs-ert:
    name: Test ert docs
    needs: [build-wheels]
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: './.github/actions/install_dependencies'
      with:
        os: ${{ matrix.os }}

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get wheels
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.os }} Python ${{ matrix.python-version }} wheel

    - name: Install wheel and test dependencies
      run: |
        find . -name "*.whl" -exec pip install {} \;
        pip install -r dev-requirements.txt

    - name: Make test directory
      run: |
        mkdir tmp_tests
        mv tests tmp_tests/tests
        mv test-data tmp_tests/test-data
        mv setup.cfg tmp_tests/setup.cfg
        mkdir tmp_tests/.git

    - name: Test docs
      run: |
        sphinx-build -n -v -E -W ./docs/rst/manual ./tmp/ert_docs

  tests-libres:
    name: Run libres tests
    needs: [build-wheels]
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest]
        # Excluded to keep build times down on Github actions
        exclude:
          - os: macos-latest
            python-version: '3.9'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: './.github/actions/install_dependencies'
      with:
        os: ${{ matrix.os }}
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get wheels
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.os }} Python ${{ matrix.python-version }} wheel

    - name: Install wheel and test dependencies
      run: |
        find . -name "*.whl" -exec pip install {} \;
        pip install -r dev-requirements.txt

    - name: Run Python tests
      run: |
        # Run tests
        pushd tests
        pytest libres_tests --durations=0
        git status --porcelain | sed '/ert.*.whl$/d'
        test -z "$(git status --porcelain | sed '/ert.*.whl$/d')"


  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build-test-cmake, tests-libres, tests-ert, docs-ert]

    # If this is a tagged release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - name: Get wheels
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Move to dist/
        run: |
          mkdir dist
          find artifacts -name "*.whl" -exec mv '{}' dist/ \;

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: statoil-travis
          password: ${{ secrets.pypi_password }}
