on:
  workflow_call:
    inputs:
      python-version:
        type: string

jobs:
  build-wheels:
    timeout-minutes: 30
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Pin git Linux
      run: |
        sudo apt-get update
        sudo apt-get remove git git-man
        sudo apt-get install git=1:2.34.1-1ubuntu1.10
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Linux Wheel
      uses: docker://quay.io/pypa/manylinux2014_x86_64
      with:
        entrypoint: /github/workspace/ci/github/build_linux_wheel.sh
        args: ${{ inputs.python-version }}

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-latest Python ${{ inputs.python-version }} wheel
        path: dist/*
