on:
  workflow_call:
    inputs:
      python-version:
        type: string
jobs:

  build-wheels:
    timeout-minutes: 30
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build Linux Wheel
      uses: docker://quay.io/pypa/manylinux2014_x86_64
      with:
        entrypoint: /github/workspace/ci/github/build_linux_wheel.sh
        args: ${{ inputs.python-version }}

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-latest Python ${{ inputs.python-version }} wheel
        path: dist/*
