on:
  workflow_call:
    inputs:
      python-version:
        type: string
      os:
        type: string

jobs:
  build-wheels:
    timeout-minutes: 45
    strategy:
      fail-fast: false

    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: ${{ inputs.python-version }}

    - name: Build macOS Wheel
      run: pip wheel . --no-deps -w dist

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.os }} Python ${{ inputs.python-version }} wheel
        path: dist/*
