name: Test old parser
on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  # We don't cancel on protected branches which codecov uses as a base
  cancel-in-progress: ${{ ! github.ref_protected }}

env:
  ERT_SHOW_BACKTRACE: 1
  ECL_SKIP_SIGNAL: 1
  USE_OLD_ERT_PARSER: "YES"
  USE_OLD_ERT_OBS_PARSER: "YES"

jobs:
  python-test-coverage-lark:
    name: Test old Parser
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: ['integration-tests', 'unit-tests', 'gui-tests']
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install with dependencies
      run: |
        pip install .
        pip install -r dev-requirements.txt

    - name: Test GUI
      if: matrix.test-type == 'gui-tests'
      timeout-minutes: 10
      run: |
        pytest tests/ --cov=ert --mpl --hypothesis-profile=ci -m "requires_window_manager" --cov-report=xml:cov.xml

    - name: Test Integration
      if: matrix.test-type == 'integration-tests'
      run: |
        pytest tests/ --cov=ert --hypothesis-profile=ci -m "integration_test" --cov-report=xml:cov.xml

    - name: Test units
      if: matrix.test-type == 'unit-tests'
      run: |
        pytest tests/ --cov=ert --hypothesis-profile=ci -m "not integration_test and not requires_window_manager" --cov-report=xml:cov.xml

    - name: Upload python coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: cov.xml
