name: Test new parser
on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ERT_SHOW_BACKTRACE: 1
  ECL_SKIP_SIGNAL: 1

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10' ]
    uses: ./.github/workflows/build-wheels-linux.yml
    with:
      python-version: ${{ matrix.python-version }}

  test-linux:
    needs: [build-linux]
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10' ]
        os: [ ubuntu-latest ]
        test-type: [ 'integration-tests', 'unit-tests', 'gui-test' ]
    uses: ./.github/workflows/test_ert.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test-type: ${{ matrix.test-type }}
