name: Python coverage

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-test-coverage:
    name: Python Coverage
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: ['integration-tests', 'unit-tests', 'gui-tests']
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: './.github/actions/install_dependencies'
      if: matrix.test-type == 'gui-tests'
      with:
        os: ubuntu-latest

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: "pipenv"
    - run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - run: pipenv install --ignore-pipfile

    - name: Install
      run: |
        pipenv run pip install .

    - name: Test GUI
      if: matrix.test-type == 'gui-tests'
      env:
        DISPLAY: ':99.0'
      run: |
        ci/github/start_herbstluftwm.sh &
        sleep 5
        pipenv run pytest tests/ --cov=ert --hypothesis-profile=ci -m "requires_window_manager" --cov-report=xml:cov.xml

    - name: Test Integration
      if: matrix.test-type == 'integration-tests'
      run: |
        pipenv run pytest tests/ --cov=ert --hypothesis-profile=ci -m "integration_test" --cov-report=xml:cov.xml

    - name: Test units
      if: matrix.test-type == 'unit-tests'
      run: |
        pipenv run pytest tests/ --cov=ert --hypothesis-profile=ci -m "not integration_test and not requires_window_manager" --cov-report=xml:cov.xml

    - name: Upload python coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: tests/cov.xml
