name: Python coverage

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

jobs:
  python-test-coverage:
    name: Python Coverage
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: ['integration', 'unit', 'gui', 'performance']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install with dependencies
      run: |
        pip install ".[dev]"

    - name: Run pytest 'tests/${{ matrix.test-type }}'
      run: |
        pytest tests/${{ matrix.test-type }} -n4 --cov=ert --cov-report=xml:cov.xml -svv --dist loadgroup

    - name: Upload python coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: cov.xml
