name: Process Dark Storage Benchmark Result
on:
  push:
    branches:
      - "gh-pages"
    paths:
      - "dev/dark_storage_performance_benchmark/output.json"
  workflow_dispatch: 

permissions:
    # deployments permission to deploy GitHub pages website
    deployments: write
    # contents permission to update benchmark contents in gh-pages branch
    contents: write

jobs:
  benchmark:
    name: Run pytest-benchmark dark storage
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          lfs: true
          ref: gh-pages

      - name: Parse and plot pytest benchmark output
        run: |
          pip install matplotlib
          dev/dark_storage_performance_benchmark/process_benchmark_result.py
          dev/dark_storage_performance_benchmark/plot_benchmark_result.py
          git config --global user.name "Dark Storage Benchmarking Workflow"
          git config --global user.email ""
          git add .
          git commit -m "Update plot dark_storage_performance_benchmark"
          git push -f origin gh-pages:gh-pages