name: Python doctest

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-doctest:
    name: 
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup_python
      with:
        python-version: '3.11'
        cache: "pip"
        cache-dependency-path: |
          setup.py
          pyproject.toml
          dev-requirements.txt

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        echo "venv/bin" >> $GITHUB_PATH

    - run: pip install .

    - name: Install with dependencies
      run: |
        pip install -r dev-requirements.txt

    - name: Test doctest
      run: |
        # dark storage assumes it is a started service so cannot be excuded
        # by pytest blindly
        pytest --doctest-modules src/ --ignore src/ert/dark_storage
