name: Python doctest

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

jobs:
  python-doctest:
    name:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup_python
      with:
        python-version: '3.11'
        cache: "pip"
        cache-dependency-path: |
          setup.py
          pyproject.toml
    - run: pip install -e ".[dev]"

    - name: Test doctest
      run: |
        # dark storage assumes it is a started service so cannot be excuded
        # by pytest blindly
        pytest --doctest-modules --cov=ert --cov-report=xml:cov.xml src/ --ignore src/ert/dark_storage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: cov.xml
