name: Python doctest

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-doctest:
    name: 
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: "pipenv"
    - run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - run: pipenv install --ignore-pipfile

    - name: Install
      run: |
        pipenv run pip install -e .

    - name: Test doctest
      run: |
        # dark storage assumes it is a started service so cannot be excuded
        # by pytest blindly
        pipenv run pytest --doctest-modules src/ --ignore src/ert/dark_storage
