name: Python test fast

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-test-fast:
    name: fast-test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      id: setup_python
      with:
        python-version: '3.11'
        cache: "pip"
        cache-dependency-path: |
          setup.py
          pyproject.toml
          dev-requirements.txt

    - name: Install with dependencies
      run: |
        pip install -U pip
        pip install .
        pip install -r dev-requirements.txt

    - name: Test
      run: |
        pytest tests -n5 --hypothesis-profile=ci -m "not requires_window_manager"
