name: Run Snake OIL demo

on:
 push:
   branches:
     - main
     - 'version-**'
 pull_request:

jobs:
  run-ert3-snakeoil:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install ERT and dependencies
      run: |
        export CC=gcc-10
        export CXX=g++-10
        pip install .

    - name: Start ert-storage
      run: |
        ert3 service start storage &
        ert3 service check storage --timeout 100

    - name: Run snake oil
      run: |
        ert3 init --example snake_oil
        pushd snake_oil
        ./run_demo
        popd
