name: Style

on:
 push:
   branches:
     - main
     - 'version-**'
 pull_request:

jobs:
  check-style:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r dev-requirements.txt

    - name: Clang Format
      run: ./script/clang-format --check

    - name: CMake Format
      run: ./script/cmake-format --check

    - name: Lint with flake8
      run: |
        flake8

    - name: Run black
      run: |
        pip install black[jupyter]
        black . --check

    - name: Run pylint
      run: |
        pip install .  # We need the dependencies of ERT to avoid import-error
        pylint ert ert3
        pylint --disable=all \
          --enable="\
            access-member-before-definition, \
            bad-thread-instantiation, \
            chained-comparison, \
            consider-iterating-dictionary, \
            consider-using-dict-items, \
            consider-using-enumerate, \
            consider-using-from-import, \
            consider-using-generator, \
            consider-using-min-builtin, \
            consider-using-set-comprehension, \
            empty-docstring, \
            expression-not-assigned, \
            no-else-break, \
            no-method-argument, \
            not-async-context-manager, \
            unsubscriptable-object, \
            pointless-statement, \
            simplifiable-if-statement, \
            subprocess-run-check, \
            super-with-arguments, \
            undefined-all-variable, \
            undefined-loop-variable, \
            unidiomatic-typecheck, \
            unneeded-not, \
            unused-import, \
            use-a-generator, \
            use-dict-literal, \
            use-maxsplit-arg, \
            useless-import-alias, \
            useless-object-inheritance \
            useless-return, \
            useless-super-delegation, \
            " \
          docs ert_data ert_gui ert_logging ert_shared job_runner res tests
        pylint --disable=all \
          --enable="consider-using-f-string" ert_data ert_gui job_runner res
