name: Style

on:
 push:
   branches:
     - main
     - 'version-**'
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-style:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r dev-requirements.txt

    - name: Clang Format
      run: ./script/clang-format --check

    - name: CMake Format
      run: ./script/cmake-format --check

    - name: Run isort
      run: |
        isort --check src/ tests/

    - name: Lint with flake8
      run: |
        flake8

    - name: Run black
      uses: psf/black@stable

    - name: Run pylint
      run: |
        pip install .  # We need the dependencies of ERT to avoid import-error
        pylint src/ert --ignore-paths=src/ert/_c_wrappers,src/ert/gui,src/ert/logging,src/ert/analysis/_es_update.py,src/ert/data,src/_ert_job_runner,src/ert/shared,src/ert/__main__.py,src/ert/cli,src/ert/ensemble_evaluator,src/ert/services
        pylint --disable=all \
          --enable="\
            access-member-before-definition, \
            arguments-differ, \
            arguments-renamed, \
            assert-on-string-literal, \
            bad-classmethod-argument, \
            bad-thread-instantiation, \
            chained-comparison, \
            comparison-with-callable, \
            consider-iterating-dictionary, \
            consider-using-dict-items, \
            consider-using-enumerate, \
            consider-using-f-string, \
            consider-using-from-import, \
            consider-using-generator, \
            consider-using-get, \
            consider-using-in, \
            consider-using-max-builtin, \
            consider-using-min-builtin, \
            consider-using-set-comprehension, \
            consider-using-with, \
            dangerous-default-value, \
            deprecated-method, \
            duplicate-key, \
            empty-docstring, \
            expression-not-assigned, \
            global-statement, \
            global-variable-not-assigned, \
            implicit-str-concat, \
            logging-not-lazy, \
            missing-final-newline, \
            no-else-break, \
            no-else-continue, \
            no-else-raise, \
            no-member, \
            no-method-argument, \
            no-value-for-parameter, \
            not-async-context-manager, \
            not-callable, \
            parse-error, \
            pointless-statement, \
            pointless-string-statement, \
            redefined-builtin, \
            redundant-unittest-assert, \
            reimported, \
            simplifiable-if-statement, \
            subprocess-run-check, \
            super-with-arguments, \
            superfluous-parens, \
            too-many-lines, \
            too-many-nested-blocks, \
            undefined-all-variable, \
            undefined-loop-variable, \
            undefined-variable, \
            unexpected-keyword-arg, \
            ungrouped-imports, \
            unidiomatic-typecheck, \
            unnecessary-comprehension, \
            unnecessary-dunder-call, \
            unnecessary-lambda, \
            unnecessary-lambda-assignment, \
            unneeded-not, \
            unsubscriptable-object, \
            unsupported-assignment-operation, \
            unsupported-binary-operation, \
            unused-import, \
            use-a-generator, \
            use-dict-literal, \
            use-implicit-booleaness-not-comparison, \
            use-maxsplit-arg, \
            used-before-assignment, \
            useless-import-alias, \
            useless-object-inheritance, \
            useless-return, \
            useless-super-delegation, \
            " \
          docs src tests test-data
