on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
      test-type:
        type: string
jobs:

  tests-ert:
    name: Run ert tests
    timeout-minutes: 30
    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        lfs: true

    - uses: actions/setup-python@v4
      id: setup_python
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: |
          setup.py
          pyproject.toml

    - name: Get wheels
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.os }} Python ${{ inputs.python-version }} wheel

    - name: Install wheel
      run: |
        find . -name "*.whl" -exec pip install "{}[dev]" \;

    - name: Unit Test
      if: inputs.test-type == 'unit-tests'
      run: |
        pytest tests -n 4 --dist loadgroup --benchmark-disable -sxv -m "not integration_test and not requires_window_manager"
