on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
      test-type:
        type: string

jobs:
  tests-ert:
    name: Run ert tests
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        lfs: true

    - uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: |
          pyproject.toml

    - name: Install HDF5 source files
      if: runner.os == 'macOS'
      run: brew install hdf5

    - name: Install ert
      run: |
        pip install ".[dev]"

    - name: Test GUI
      if: inputs.test-type == 'gui-test'
      run: |
        pytest tests --junit-xml=junit.xml -v --mpl -m "requires_window_manager" --benchmark-disable

    - name: Unit Test
      if: inputs.test-type == 'unit-tests'
      run: |
        pytest tests --junit-xml=junit.xml -n logical --show-capture=stderr -v -m "not integration_test and not requires_window_manager" --benchmark-disable --dist loadgroup

    - name: Integration Test
      if: inputs.test-type == 'integration-tests'
      run: |
        pytest tests --junit-xml=junit.xml -n logical --show-capture=stderr -v -m "integration_test and not requires_window_manager" --benchmark-disable

    - name: Test for a clean repository
      run: |
        # Run this before the 'Test CLI' entry below, which produces a few files that are accepted for now. Exclude the wheel.
        git status --porcelain | sed '/ert.*.whl$\|\/block_storage$/d'
        test -z "$(git status --porcelain | sed '/ert.*.whl$\\|\\/block_storage$/d')"

    - uses: test-summary/action@v2
      continue-on-error: true
      with:
        paths: junit.xml
      if: always()

    - name: Test CLI
      run: |
        ert --help
