name: Test Semeio

# This job checks whether current main of semeio
# is compatible with the changes. It is not required to pass
# before merging, but breakage should be followed by fix in semeio
# after merge.

on: [pull_request]

jobs:
  test-semeio:
    name: Test Semeio
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ert
      run: |
        pip install .

    - name: Get semeio
      run: |
        git clone https://github.com/equinor/semeio.git

    - name: Test semeio
      run: |
        pushd semeio
        pip install ".[test]"
        pytest
