name: Type checking

on:
 push:
   branches:
     - main
     - 'version-**'
 pull_request:

env:
  UV_SYSTEM_PYTHON: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  type-checking:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: pip install uv

    - name: Install ERT and dependencies
      run: |
        uv pip install ".[dev, types]"

    - run: echo ::add-matcher::.github/mypy-matcher.json
    - name: Run mypy
      run: |
        mypy src/ert
